# Generated by Django 3.1.7 on 2022-10-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userportfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
